-- DropForeignKey
ALTER TABLE "Post" DROP CONSTRAINT IF EXISTS "Post_authorId_fkey";
ALTER TABLE "Task" DROP CONSTRAINT IF EXISTS "Task_authorId_fkey";

-- AlterTable
ALTER TABLE "User" DROP CONSTRAINT "User_pkey";
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "id" SET DATA TYPE TEXT USING gen_random_uuid()::TEXT;
ALTER TABLE "User" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "User" ADD COLUMN "username" TEXT NOT NULL;
ALTER TABLE "User" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD CONSTRAINT "User_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "Post" DROP CONSTRAINT "Post_pkey";
ALTER TABLE "Post" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Post" ALTER COLUMN "id" SET DATA TYPE TEXT USING gen_random_uuid()::TEXT;
ALTER TABLE "Post" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "Post" ALTER COLUMN "authorId" SET DATA TYPE TEXT USING "authorId"::TEXT;
ALTER TABLE "Post" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Post" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL;
ALTER TABLE "Post" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "Post" ADD CONSTRAINT "Post_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "Task" DROP CONSTRAINT "Task_pkey";
ALTER TABLE "Task" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Task" ALTER COLUMN "id" SET DATA TYPE TEXT USING gen_random_uuid()::TEXT;
ALTER TABLE "Task" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "Task" ALTER COLUMN "authorId" SET DATA TYPE TEXT USING "authorId"::TEXT;
ALTER TABLE "Task" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "Task" ADD CONSTRAINT "Task_pkey" PRIMARY KEY ("id");

-- CreateIndex
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
